const actionTypes = {
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
};
export default actionTypes;
